eventqueue.out: eventqueue.h event.h eventqueue.m.cpp
	g++ -ggdb -o eventqueue.out event.h eventqueue.h eventqueue.m.cpp
randomgenerator.out: randomgenerator.h randomgenerator.cpp randomgenerator.m.cpp
	g++ -ggdb -o randomgenerator.out randomgenerator.h randomgenerator.cpp randomgenerator.m.cpp
clean:
	rm *.out *.o *.gch